puts "Seeding Started"
#Chest

Exercise.create(group: "Chest", name: "Barbell Bench Press", description: "The bench press, or chest press, is an upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.", form: "https://www.youtube.com/watch?v=rT7DgCr-3pg")
Exercise.create(group: "Chest", name: "Dumbbell Bench Press", description: "The dumbbell bench press, also known as the dumbbell flat bench press and the dumbbell chest press, is an upper-body exercise that activates your arm, shoulder, and chest muscles. Perform the dumbbell bench press exercise by lying flat on your back on a bench. Grab a pair of dumbbells and hold them on your hips. While engaging your core and glutes, lift the dumbbells above your chest. Squeeze your shoulder blades as you lower them again until your upper and lower arms form a 90-degree angle.", form: "https://www.youtube.com/watch?v=VmB1G1K7v94")
Exercise.create(group: "Chest", name: "Incline Bench Press", description: "The Incline Bench Press is a version of the traditional Bench Press in which the bench is positioned at about a 45-degree angle. The resulting inclined position targets your upper chest and the frontside of your shoulders more the standard flat bench.", form: "https://www.youtube.com/watch?v=DbFgADa2PL8")
Exercise.create(group: "Chest", name: "Decline Press", description: "It's a variation of the flat bench press, a popular chest workout. In a decline bench press, the bench is set to 15 to 30 degrees on a decline. This angle places your upper body on a downward slope, which activates the lower pectoral muscles as you push weights away from your body.", form: "https://www.youtube.com/watch?v=LfyQBUKR8SE")
Exercise.create(group: "Chest", name: "Machine Chest Press", description: "The chest press helps build the pectoral muscles while also working the biceps, deltoids, and latissimus dorsi. The seated chest press is an upright version of the lying bench press and a great addition to an upper-body strength workout.", form: "https://www.youtube.com/watch?v=xUm0BiZCWlQ")
Exercise.create(group: "Chest", name: "Push-Up", description: "A push-up is a common calisthenics exercise beginning from the prone position. By raising and lowering the body using the arms, push-ups exercise the pectoral muscles, triceps, and anterior deltoids, with ancillary benefits to the rest of the deltoids, serratus anterior, coracobrachialis and the midsection as a whole.", form: "https://www.youtube.com/watch?v=IODxDxX7oi4")
Exercise.create(group: "Chest", name: "Dip", description: "Dips are a bodyweight exercise that develops the triceps and other upper-body muscles. The exercise begins when you hold on to parallel bars with your arms straight. You then bend your elbows until your upper arms are parallel to the ground before driving up to the starting position.", form: "https://www.youtube.com/watch?v=2z8JmcrW-As")
Exercise.create(group: "Chest", name: "Chest Fly", description: "The chest fly or pectoral fly (abbreviated to pec fly) primarily works the pectoralis major muscles to move the arms horizontally forward. If medially (internally) rotated, it is assisted in this by the anterior (front) head of the deltoideus in transverse flexion. If laterally (externally) rotated, the contribution of the deltoid is lessened and the pec major is strongly emphasized as the transverse adductor.", form: "https://www.youtube.com/watch?v=eozdVDA78K0")
Exercise.create(group: "Chest", name: "Dumbbell Pull-Over", description: "The dumbbell pullover is a weightlifting exercise that targets your pecs and lat muscles. Perform the dumbbell pullover exercise by grabbing a single dumbbell and lying back on a flat bench. Keep your lower back in contact with the bench and engage your core. With straight arms, extend the dumbbell above your chest.", form: "https://www.youtube.com/watch?v=ZhPOEQJRzBU")
Exercise.create(group: "Chest", name: "Machine Fly", description: "A machine fly, alternatively called a seated lever fly, is a strength training exercise based on the free weight chest fly. As with the chest fly, the hand and arm move through an arc while the elbow is kept at a constant angle. Flyes are used to work the muscles of the upper body, primarily the sternal head of the pectoralis major.", form: "https://www.youtube.com/watch?v=Z57CtFmRMxA")

#Back

Exercise.create(group: "Back", name: "Deadlift", description: "The deadlift is a movement in which your hips hinge backward to lower down and pick up a weighted barbell or kettlebell from the floor. Your back is flat throughout the movement. ", form: "https://www.youtube.com/watch?v=JCXUYuzwNrM")
Exercise.create(group: "Back", name: "Bent-Over Row", description: "Grip a barbell with palms down so that the wrists, elbows, and shoulders are in a straight line. Lift the bar from the rack, bend forward at the hips, and keep the back straight with a slight bend in the knees. Lower the bar towards the floor until the elbows are completely straight, and keep the back flat as the bar is pulled towards the belly button. Then slowly lower the bar to the starting position and repeat. ", form: "https://www.youtube.com/watch?v=9efgcAjQe7E")
Exercise.create(group: "Back", name: "Pull-Up", description: "A pull-up is an upper-body strength exercise. The pull-up is a closed-chain movement where the body is suspended by the hands and pulls up. As this happens, the elbows flex and the shoulders adduct and extend to bring the elbows to the torso.", form: "https://www.youtube.com/watch?v=ylVmNQlKdAI")
Exercise.create(group: "Back", name: "T-Bar Row", description: "The T-Bar row, also known as the close grip barbell row, is an excellent exercise to use if you are trying to target your upper back. A variation of the bent over row, the T-bar row allows one to utilize a more neutral grip which can help alleviate some of the tension placed on the shoulder joint.", form: "https://www.youtube.com/watch?v=j3Igk5nyZE4")
Exercise.create(group: "Back", name: "Seated Row", description: "The seated row is an exercise you can do with a weight machine to work the muscles in your upper back. Specifically, the seated row targets the muscles in your upper back and also the latissimus dorsi — a muscle on the outer side of the chest wall.", form: "https://www.youtube.com/watch?v=GZbfZ033f74")
Exercise.create(group: "Back", name: "Single-Arm Smith Machine Row", description: "With the bar at thigh level, load an appropriate weight. Take a wide grip on the bar and unhook the weight, removing your off hand from the bar. Your arm should be extended as you stand up straight with your head and chest up. This will be your starting position. Begin the movement by flexing the elbow, raising the upper arm with the elbow pointed out. Continue until your upper arm is parallel to the floor. After a brief pause, return the weight to the starting position. Repeat for the desired number of repetitions before engaging the hooks to rack the weight.", form: "https://www.youtube.com/watch?v=pOMneROHGYY")
Exercise.create(group: "Back", name: "Lat Pull-Down", description: "The pulldown exercise works the back muscles and is performed at a workstation with adjustable resistance, usually plates. While seated, you pull a hanging bar down toward you, to reach chin level, and then release it back up with control for one repetition.", form: "https://www.youtube.com/watch?v=CAwf7n6Luuc")
Exercise.create(group: "Back", name: "Single-Arm Dumbbell Row", description: "Assume a standing position while holding a dumbbell in one hand with a neutral grip. Hinge forward until your torso is roughly parallel with the floor (or slightly above) and then begin the movement by driving the elbow behind the body while retracting the shoulder blade. Pull the dumbbell towards your body until the elbow is at (or just past) the midline and then slowly lower the dumbbell back to the starting position under control. Repeat for the desired number of repetitions on both sides.", form: "https://www.youtube.com/watch?v=pYcpY20QaE8")
Exercise.create(group: "Back", name: "Dumbbell Pull-Over", description: "The dumbbell pullover is a weightlifting exercise that targets your pecs and lat muscles. Perform the dumbbell pullover exercise by grabbing a single dumbbell and lying back on a flat bench. Keep your lower back in contact with the bench and engage your core. With straight arms, extend the dumbbell above your chest. Carefully lower the dumbbell behind your head before returning it to the starting position above you.", form: "https://www.youtube.com/watch?v=ZhPOEQJRzBU")
Exercise.create(group: "Back", name: "Chest-Supported Row", description: "Using a neutral grip, lean into an incline bench. Take a dumbbell in each hand with a neutral grip, beginning with the arms straight. This will be your starting position. Retract the shoulder blades and flex the elbows to row the dumbbells to your side. Pause at the top of the motion, and then return to the starting position.", form: "https://www.youtube.com/watch?v=H75im9fAUMc")

#Biceps

Exercise.create(group: "Biceps", name: "Barbell or EZ-Bar Curl", description: "Stand with your feet shoulder-width apart, knees slightly bent. Hold an EZ-bar in an underhand grip with your arms extended and then curl the bar up towards your chest, keeping your elbows in to your sides.", form: "https://www.youtube.com/watch?v=zG2xJ0Q5QtI")
Exercise.create(group: "Biceps", name: "Cable Curl", description: "The standing bicep cable curl is an exercise that trains the biceps in isolation, and places the muscles under constant tension throughout both the concentric and eccentric phases. It essentially involves standing in front of the cable machine and pulling the attached bar or handles upwards in a curling motion, as you would during a regular free weight bicep curl.", form: "https://www.youtube.com/watch?v=AsAVbj7puKo")
Exercise.create(group: "Biceps", name: "Dumbbell Curl", description: "Hold a dumbbell in each hand and stand with your feet as wide apart as your hips. Let your arms hang down at your sides with your palms forward. Pull your abdominals in, stand tall, and keep your knees slightly bent. Curl both arms upward until they're in front of your shoulders. Slowly lower the dumbbells back down.", form: "https://www.youtube.com/watch?v=sAq_ocpRh_I")
Exercise.create(group: "Biceps", name: "Chin-Up", description: "An exercise in which one hangs by the hands from a support (such as a horizontal bar) and pulls oneself up until the chin is level with the support specifically : such an exercise done with the palms facing inward.", form: "https://www.youtube.com/watch?v=40A3NGv31lE")
Exercise.create(group: "Biceps", name: "Reverse-Grip Barbell Row", description: "Stand erect while holding a barbell with a supinated grip (palms facing up). Bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position. While keeping the torso stationary, lift the barbell as you breathe out, keeping the elbows close to the body and not doing any force with the forearm other than holding the weights. On the top contracted position, squeeze the back muscles and hold for a second. Slowly lower the weight again to the starting position as you inhale.", form: "https://www.youtube.com/watch?v=3gdGSSgDby8")
Exercise.create(group: "Biceps", name: "Hammer Curl", description: "Stand up straight with a dumbbell in each hand, holding them alongside you. Your palms should face your body. Keep your feet hip-width apart and engage your core to stabilize the body. Keep your biceps stationary and start bending at your elbows, lifting both dumbbells. Lift until the dumbbells reach shoulder-level, but don’t actually touch your shoulders. Hold this contraction briefly, then lower back to the starting position and repeat.", form: "https://www.youtube.com/watch?v=zC3nLlEvin4")
Exercise.create(group: "Biceps", name: "Incline Curl", description: "Hold a dumbbell in each hand and lie back on an incline bench. The dumbbells should be at arm's length hanging at your sides and your palms should be facing out. This will be your starting position. Now as you exhale curl the weight outward and up while keeping your forearms in line with your side deltoids. Continue the curl until the dumbbells are at shoulder height and to the sides of your deltoids. Tip: The end of the movement should look similar to a double biceps pose. After a second contraction at the top of the movement, start to inhale and slowly lower the weights back to the starting position using the same path used to bring them up.", form: "https://www.youtube.com/watch?v=soxrZlIl35U")
Exercise.create(group: "Biceps", name: "Concentration Curl", description: "Concentration curls, also known as dumbbell concentration curls, are a variation on traditional biceps curls. Perform concentration curls by sitting on a bench, resting the back of your upper arm against your inner thigh, and lifting a dumbbell.", form: "https://www.youtube.com/watch?v=Jvj2wV0vOYU")
Exercise.create(group: "Biceps", name: "Preacher Curl", description: "A weightlifting exercise for the biceps in which a barbell is lifted by flexing the elbows, with the upper arms resting on an angled bench.", form: "https://www.youtube.com/watch?v=nbcgEmZ0Be4")
Exercise.create(group: "Biceps", name: "Drag Curl", description: "Grab a barbell with a supinated grip (palms facing forward) and get your elbows close to your torso and back. This will be your starting position. As you exhale, curl the bar up while keeping the elbows to the back as you drag the bar up by keeping it in contact with your torso. Tip: As you can see, you will not be keeping the elbows pinned to your sides, but instead you will be bringing them back. Also, do not lift your shoulders. Slowly go back to the starting position as you keep the bar in contact with the torso at all times.", form: "https://www.youtube.com/watch?v=LMdNTHH6G8I")

#Triceps

Exercise.create(group: "Triceps", name: "Skullcrusher", description: "Using a close grip, lift the EZ bar and hold it with your elbows in as you lie on the bench. Your arms should be perpendicular to the floor. This will be your starting position. Keeping the upper arms stationary, lower the bar by allowing the elbows to flex. Inhale as you perform this portion of the movement. Pause once the bar is directly above the forehead. Lift the bar back to the starting position by extending the elbow and exhaling.", form: "https://www.youtube.com/watch?v=d_KZxkY_0cM")
Exercise.create(group: "Triceps", name: "Close-Grip Bench Press", description: "Lie back on a flat bench. Using a close grip (around shoulder width), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position. As you breathe in, come down slowly until you feel the bar on your middle chest. Tip: Make sure that - as opposed to a regular bench press - you keep the elbows close to the torso at all times in order to maximize triceps involvement. After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your triceps muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again.", form: "https://www.youtube.com/watch?v=nEF0bv2FW94")
Exercise.create(group: "Triceps", name: "Triceps Dip", description: "To get into the starting position, hold your body at arm's length with your arms nearly locked above the bars. Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement. Lower yourself until there is a 90 degree angle formed between the upper arm and forearm. Then, exhale and push your torso back up using your triceps to bring your body back to the starting position.", form: "https://www.youtube.com/watch?v=35PXVWP1XVs")
Exercise.create(group: "Triceps", name: "Bench Dip", description: "Bench dips are a bodyweight exercise designed to activate muscles in your arms, shoulders, and chest. They are also known as triceps dips. Perform bench dips by sitting on a bench or elevated surface with your lower body extended to the floor in front of you. While placing your hands shoulder-width apart on the edge of the bench, slowly lower your body until your upper arm and forearm form a 90-degree angle.", form: "https://www.youtube.com/watch?v=c3ZGl4pAwZ4")
Exercise.create(group: "Triceps", name: "Triceps Machine Dip", description: "Sit securely in a dip machine, select the weight and firmly grasp the handles. Now keep your elbows in at your sides in order to place emphasis on the triceps. The elbows should be bent at a 90 degree angle. As you contract the triceps, extend your arms downwards as you exhale. Tip: At the bottom of the movement, focus on keeping a little bend in your arms to keep tension on the triceps muscle. Now slowly let your arms come back up to the starting position as you inhale.", form: "https://www.youtube.com/watch?v=Uv6poyDWsUo")
Exercise.create(group: "Triceps", name: "Board Press", description: "Begin by lying on the bench, getting your head beyond the bar if possible. One to five boards, made out of 2x6's, can be screwed together and held in place by a training partner, bands, or just tucked under your shirt. Tuck your feet underneath you and arch your back. Using the bar to help support your weight, lift your shoulder off the bench and retract them, squeezing the shoulder blades together. Use your feet to drive your traps into the bench. Maintain this tight body position throughout the movement. You can take a standard bench grip, or shoulder width to focus on the triceps. Pull the bar out of the rack without protracting your shoulders. The bar, wrist, and elbow should stay in line at all times. Focus on squeezing the bar and trying to pull it apart. Lower the bar to the boards, and then drive the bar up with as much force as possible. The elbows should be tucked in until lockout.", form: "https://www.youtube.com/watch?v=XeScw6pghNw")
Exercise.create(group: "Triceps", name: "Dumbbell Overhead Triceps Extension", description: "Sit down on a bench with back support and grasp a dumbbell with both hands and hold it overhead at arm's length. Tip: a better way is to have somebody hand it to you especially if it is very heavy. The resistance should be resting in the palms of your hands with your thumbs around it. The palm of the hand should be facing inward. This will be your starting position. Keeping your upper arms close to your head (elbows in) and perpendicular to the floor, lower the resistance in a semi-circular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step.
Go back to the starting position by using the triceps to raise the dumbbell. Breathe out as you perform this step.", form: "https://www.youtube.com/watch?v=YbX7Wd8jQ-Q")
Exercise.create(group: "Triceps", name: "Cable Overhead Extension with Rope", description: "Attach a rope to a low pulley. After selecting an appropriate weight, grasp the rope with both hands and face away from the cable. Position your hands behind your head with your elbows point straight up. Your elbows should start out flexed, and you can stagger your stance and lean gently away from the machine to create greater stability. This will be your starting position. To perform the movement, extend through the elbow while keeping the upper arm in position, raising your hands above your head. Squeeze your triceps at the top of the movement, and slowly lower the weight back to the start position.", form: "https://www.youtube.com/watch?v=GzmlxvSFE7A")
Exercise.create(group: "Triceps", name: "Single-Arm Cable Kick-Back", description: "Attach a single handle low down on the cable machine. Hold the handle in an overhand grip and step away from the machine so there is tension in the cable. Bend at the hips so your upper body is parallel to the ground, with your arm by your side and bent at 90° at the elbow. Straighten your arm behind you to perform the kick-back, then slowly bring the handle back to the starting position.", form: "https://www.youtube.com/watch?v=8yTabH46T1s")
Exercise.create(group: "Triceps", name: "Cable Push-Down", description: "Attach a V-Bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width. Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. The thumbs should be higher than the small finger. This is your starting position. Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement. After a second hold at the contracted position, bring the V-Bar slowly up to the starting point. Breathe in as you perform this step.", form: "https://www.youtube.com/watch?v=2-LAMcpzODU")

#Shoulders

Exercise.create(group: "Shoulders", name: "Push-Press", description: "The push press is an overhead press variant that uses the legs to create power. To begin the lift, the legs bend to an athletic dip position, followed by a speedy extension of the body to drive the weight overhead. A successful completion of the lift ends with the bar overhead, with both the arms and legs straight.", form: "https://www.youtube.com/watch?v=ep30avTSMB0")
Exercise.create(group: "Shoulders", name: "Military Press", description: "Start by placing a barbell that is about chest high on a squat rack. Once you have selected the weights, grab the barbell using a pronated (palms facing forward) grip. Make sure to grip the bar wider than shoulder width apart from each other. Slightly bend the knees and place the barbell on your collar bone. Lift the barbell up keeping it lying on your chest. Take a step back and position your feet shoulder width apart from each other. Once you pick up the barbell with the correct grip length, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position. Lower the bar down to the collarbone slowly as you inhale. Lift the bar back up to the starting position as you exhale.", form: "https://www.youtube.com/watch?v=2yjwXTZQDDI")
Exercise.create(group: "Shoulders", name: "Rear Delt Row", description: "Using a neutral grip, lean into an incline bench. Take a dumbbell in each hand with a neutral grip, beginning with the arms straight. This will be your starting position. Retract the shoulder blades and flex the elbows to row the dumbbells to your side. Pause at the top of the motion, and then return to the starting position.", form: "https://www.youtube.com/watch?v=2LxN3_3atps")
Exercise.create(group: "Shoulders", name: "Seated Dumbbell Press", description: "Grab a couple of dumbbells and sit on a military press bench or a utility bench that has a back support on it as you place the dumbbells upright on top of your thighs. Clean the dumbbells up one at a time by using your thighs to bring the dumbbells up to shoulder height at each side. Rotate the wrists so that the palms of your hands are facing forward. This is your starting position. As you exhale, push the dumbbells up until they touch at the top. After a second pause, slowly come down back to the starting position as you inhale.", form: "https://www.youtube.com/watch?v=qEwKCR5JCog")
Exercise.create(group: "Shoulders", name: "Seated Barbell Press", description: "Sit on a Military Press Bench with a bar behind your head and either have a spotter give you the bar (better on the rotator cuff this way) or pick it up yourself carefully with a pronated grip (palms facing forward). Tip: Your grip should be wider than shoulder width and it should create a 90-degree angle between the forearm and the upper arm as the barbell goes down. Once you pick up the barbell with the correct grip length, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position. Lower the bar down to the collarbone slowly as you inhale. Lift the bar back up to the starting position as you exhale.", form: "https://www.youtube.com/watch?v=oBGeXxnigsQ")
Exercise.create(group: "Shoulders", name: "Upright Row", description: "Grasp a barbell with an overhand grip that is slightly less than shoulder width. The bar should be resting on the top of your thighs with your arms extended and a slight bend in your elbows. Your back should also be straight. This will be your starting position. Now exhale and use the sides of your shoulders to lift the bar, raising your elbows up and to the side. Keep the bar close to your body as you raise it. Continue to lift the bar until it nearly touches your chin. Tip: Your elbows should drive the motion, and should always be higher than your forearms. Remember to keep your torso stationary and pause for a second at the top of the movement. Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.", form: "https://www.youtube.com/watch?v=amCU-ziHITM")
Exercise.create(group: "Shoulders", name: "Arnold Press", description: "Sit on an exercise bench with back support and hold two dumbbells in front of you at about upper chest level with your palms facing your body and your elbows bent. Tip: Your arms should be next to your torso. The starting position should look like the contracted portion of a dumbbell curl. Now to perform the movement, raise the dumbbells as you rotate the palms of your hands until they are facing forward. Continue lifting the dumbbells until your arms are extended above you in straight arm position. Breathe out as you perform this portion of the movement. After a second pause at the top, begin to lower the dumbbells to the original position by rotating the palms of your hands towards you. Tip: The left arm will be rotated in a counter clockwise manner while the right one will be rotated clockwise. Breathe in as you perform this portion of the movement.", form: "https://www.youtube.com/watch?v=6Z15_WdXmVw")
Exercise.create(group: "Shoulders", name: "Rear Delt Fly", description: "For this exercise, you will need a pair of dumbbells. Assume a standing position with your feet shoulder width apart. Hinge at the waist until your back is nearly parallel to the floor. With your arms slightly bent, contract your rear deltoids to bring the weight up and out to your sides. Squeeze your shoulder blades together at the top of the rep. Slowly bring your arms back down to the starting position. Maintain tightness in your core and repeat!", form: "https://www.youtube.com/watch?v=0GSu6Z-Oj7U")
Exercise.create(group: "Shoulders", name: "Lateral Raise", description: "Grab a set of dumbbells and stand straight. With your palms facing down, lift the dumbbells and raise your arms out to the sides. Once your elbows are at shoulder height, pause, and then slowly lower the arms back to the initial position.", form: "https://www.youtube.com/watch?v=3VcKaXpzqRo")
Exercise.create(group: "Shoulders", name: "Front Raise", description: "Adopt a pronated, shoulder-width grip on the barbell from a standing position. Allow your arms to hang straight down to mid thigh with the elbows extended. Your head should face forward, with your shoulders back and your chest up. Maintain a neutral spine and contract your abs to provide core support. This will be your starting position. Initiate the movement by flexing the shoulder, raising the weight straight out in front of you. Keep the elbows extended and the wrist neutral throughout the movement. Continue the upward movement of the arms until the barbell is just above shoulder height. At the top of the motion, pause briefly, and then slowly return to the starting position.", form: "https://www.youtube.com/watch?v=Ofo2DQdT7DA")

#Legs

Exercise.create(group: "Legs", name: "Barbell Back Squat", description: "Begin by loading the bar appropriately and stepping under it, placing it across the back of the shoulders slightly below the rear deltoids. Squeeze your shoulder blades together and rotate your elbows forward, attempting to bend the bar across your shoulders. Remove the bar from the rack, creating a tight arch in your lower back, and step back into position. Place your feet in a wider-than-shoulder-width stance with the toes slightly pointed out and knees slightly bent. Keep your neck neutral. This will be your starting position. Descend into a squat by pushing your hips and butt backwards. Continue down until the upper legs are at or just below parallel to the floor. Inhale as you perform this portion of the movement. Descend into a squat by pushing your hips and butt backwards. Continue down until the upper legs are at or just below parallel to the floor. Inhale as you perform this portion of the movement. Drive up through your heels, pushing your feet and knees out. Continue upward, maintaining tightness head to toe, until you have returned to the starting position.", form: "https://www.youtube.com/watch?v=SW_C1A-rejs")
Exercise.create(group: "Legs", name: "Barbell Front Squat", description: "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, bring your arms up under the bar while keeping the elbows high and the upper arm slightly above parallel to the floor. Rest the bar on top of the deltoids and cross your arms while grasping the bar for total control. Lift the bar off the rack by first pushing with your legs and at the same time straightening your torso. Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section). Begin to slowly lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly. Begin to raise the bar as you exhale by pushing the floor mainly with the middle of your foot as you straighten the legs again and go back to the starting position.", form: "https://www.youtube.com/watch?v=tlfahNdNPPI")
Exercise.create(group: "Legs", name: "Deadlift", description: "The deadlift is a weight training exercise in which a loaded barbell or bar is lifted off the ground to the level of the hips, torso perpendicular to the floor, before being placed back on the ground. ", form: "https://www.youtube.com/watch?v=ytGaGIn3SjE")
Exercise.create(group: "Legs", name: "Split Squat", description: "Start by standing about 2 to 3 feet in front of a flat bench with your back facing the bench. Have a barbell in front of you on the floor. Tip: Your feet should be shoulder width apart from each other. Bend the knees and use a pronated grip with your hands being wider than shoulder width apart from each other to lift the barbell up until you can rest it on your chest. Then lift the barbell over your head and rest it on the base of your neck. Move one foot back so that your toe is resting on the flat bench. Your other foot should be stationary in front of you. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. Tip: Make sure your back is straight and chest is out while performing this exercise. As you inhale, slowly lower your leg until your thigh is parallel to the floor. At this point, your knee should be over your toes. Your chest should be directly above the middle of your thigh. Leading with the chest and hips and contracting the quadriceps, elevate your leg back to the starting position as you exhale. After the desired repetitions switch legs and repeat the movement.", form: "https://www.youtube.com/watch?v=r1jukGZPnZI")
Exercise.create(group: "Legs", name: "Hack Squat", description: "Place the back of your torso against the back pad of the machine and hook your shoulders under the shoulder pads provided. Position your legs in the platform using a shoulder width medium stance with the toes slightly pointed out. Tip: Keep your head up at all times and also maintain the back on the pad at all times. Place your arms on the side handles of the machine and disengage the safety bars (which on most designs is done by moving the side handles from a facing front position to a diagonal position). Now straighten your legs without locking the knees. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section). Begin to slowly lower the unit by bending the knees as you maintain a straight posture with the head up (back on the pad at all times). Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly. 	Begin to raise the unit as you exhale by pushing the floor with mainly with the heel of your foot as you straighten the legs again and go back to the starting position.", form: "https://www.youtube.com/watch?v=aejeH1c2GWA")
Exercise.create(group: "Legs", name: "Lunge", description: "Grasping a dumbbell in both hands, stand with your feet shoulder-width apart. This will be your starting position. Step forward with one leg, flexing the knees to drop your hips. Descend until your rear knee touches the ground. Your posture should remain upright, and your front knee should stay above the front foot. Drive through the heel of your lead foot and extend both knees to raise yourself back up. Step forward with your rear foot, repeating the lunge on the opposite leg.", form: "https://www.youtube.com/watch?v=D7KaRcUTQeE")
Exercise.create(group: "Legs", name: "Leg Press", description: "The leg press, a type of resistance training exercise, is an excellent way to strengthen your legs. It's done by pushing your legs against weights on a leg press machine.", form: "https://www.youtube.com/watch?v=IZxyjW7MPJQ")
Exercise.create(group: "Legs", name: "Romanian Deadlift", description: "Hold a bar at hip level with a pronated (palms facing down) grip. Your shoulders should be back, your back arched, and your knees slightly bent. This will be your starting position. Lower the bar by moving your butt back as far as you can. Keep the bar close to your body, your head looking forward, and your shoulders back. Done correctly, you should reach the maximum range of your hamstring flexibility just below the knee. Any further movement will be compensation and should be avoided for this movement. At the bottom of your range of motion, return the starting position by driving the hips forward to stand up tall.", form: "https://www.youtube.com/watch?v=JCXUYuzwNrM")
Exercise.create(group: "Legs", name: "Leg Curl", description: "The hamstring curl, also called a leg curl, is an exercise that strengthens the hamstrings. It involves bending your knees and moving your heels toward your butt while the rest of your body stays still. Typically, the exercise is done on a leg curl machine.", form: "https://www.youtube.com/watch?v=ELOCsoDSmrg")

#Abdominals

Exercise.create(group: "Abdominals", name: "Hanging Knee Raise", description: "Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position. Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so. Go back slowly to the starting position as you breathe in.", form: "https://www.youtube.com/watch?v=hdng3Nm1x_E")
Exercise.create(group: "Abdominals", name: "Machine Crunch", description: "The machine crunch is a machine-based exercise targeting the abdominal muscles. It involves sitting upright in the machine and curling the torso down toward the chest against some pre-set level of resistance.", form: "https://www.youtube.com/watch?v=_O1xunCfYEM")
Exercise.create(group: "Abdominals", name: "Pallof Press", description: "Connect a standard handle to a tower, and if possible, position the cable to shoulder height. If not, a low pulley will suffice. With your side to the cable, grab the handle with both hands and step away from the tower. You should be approximately arm's length away from the pulley, with the tension of the weight on the cable. With your feet positioned hip-width apart and knees slightly bent, hold the cable to the middle of your chest. This will be your starting position. Press the cable away from your chest, fully extending both arms. You core should be tight and engaged. Hold the repetition for several seconds before returning to the starting position. At the conclusion of the set, repeat facing the other direction.", form: "https://www.youtube.com/watch?v=gHGLwQGvtxg")
Exercise.create(group: "Abdominals", name: "Cable Crunch", description: "Kneel below a high pulley that contains a rope attachment. Grasp cable rope attachment and lower the rope until your hands are placed next to your face. Flex your hips slightly and allow the weight to hyperextend the lower back. This will be your starting position. With the hips stationary, flex the waist as you contract the abs so that the elbows travel towards the middle of the thighs. Exhale as you perform this portion of the movement and hold the contraction for a second. Slowly return to the starting position as you inhale. Tip: Make sure that you keep constant tension on the abs throughout the movement. Also, do not choose a weight so heavy that the lower back handles the brunt of the work.", form: "https://www.youtube.com/watch?v=2fbujeH3F0E")
Exercise.create(group: "Abdominals", name: "Decline Crunch", description: "Secure your legs at the end of the decline bench and slowly lay down on the bench. Raise your upper body off the bench until your torso is about 35-45 degrees if measured from the floor. Put one hand beside your head and the other on your thigh. This will be your starting position. Raise your upper body slowly from the starting position while turning your torso to the left. Continue crunching up as you exhale until your right elbow touches your left knee. Hold this contracted position for a second. Tip: Focus on keeping your abs tight and keeping the movement slow and controlled. Lower your body back down slowly to the starting position as you inhale. After completing one set on the right for the recommended amount of repetitions, switch to your left side. Tip: Focus on really twisting your torso and feeling the contraction when you are in the up position.", form: "https://www.youtube.com/watch?v=FeaqKRoc1Jc")
Exercise.create(group: "Abdominals", name: "Squat", description: "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, bring your arms up under the bar while keeping the elbows high and the upper arm slightly above parallel to the floor. Rest the bar on top of the deltoids and cross your arms while grasping the bar for total control. Lift the bar off the rack by first pushing with your legs and at the same time straightening your torso. Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section). Begin to slowly lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly. Begin to raise the bar as you exhale by pushing the floor mainly with the middle of your foot as you straighten the legs again and go back to the starting position.", form: "https://www.youtube.com/watch?v=tlfahNdNPPI")
Exercise.create(group: "Abdominals", name: "Russian Twist", description: "Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees. Elevate your upper body so that it creates an imaginary V-shape with your thighs. Your arms should be fully extended in front of you perpendicular to your torso and with the hands clasped. This is the starting position. Twist your torso to the right side until your arms are parallel with the floor while breathing out. Hold the contraction for a second and move back to the starting position while breathing out. Now move to the opposite side performing the same techniques you applied to the right side.", form: "https://www.youtube.com/watch?v=pDTHSnoGoEc")
Exercise.create(group: "Abdominals", name: "Ab Roll-Out", description: "Hold an ab-wheel or barbell with rotating sleeves with straight arms either kneeling or standing depending on your strength, the wheel close to the knees or feet. Roll the wheel out until your body is flat and roll back to the starting position. From the start, forcefully contract the abs to create a position with the pelvis slightly posteriorly tilted (i.e. lower back flat) and do not allow this position to change—avoid hyperextension of the lower back.", form: "https://www.youtube.com/watch?v=A3uK5TPzHq8")
Exercise.create(group: "Abdominals", name: "Exercise Ball Pike", description: "Begin in a plank position with feet on the ball and hands on floor just below your shoulders. As you exhale, lift your hips up and pull your feet toward your midline until your body forms an upside down V. As you inhale, return to plank position. Tighten your abdominals to avoid letting your back sag.", form: "https://www.youtube.com/watch?v=4YOKVI9aSjE")
Exercise.create(group: "Abdominals", name: "Plank", description: "Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder. Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised.", form: "https://www.youtube.com/watch?v=pSHjTRCQxIw")

puts "Seeding Done"